#! /bin/sh
### BEGIN INIT INFO
# Provides:          asplashscreen
# Required-Start:
# Required-Stop:
# Should-Start:      
# Default-Start:     S
# Default-Stop:
# Short-Description: Show custom splashscreen
# Description:       Show custom splashscreen
### END INIT INFO


do_start () {
    # Solution la plus rapide si l'on veut utiliser le logo par défaut
    dd if=/root/logojukidbox.fb of=/dev/fb0 bs=1091584 count=1 > /dev/null 2>&1
    
    # Solution plus générique si l'on veut utiliser n'importe quel JPG/PNG
    # /usr/bin/fbv --noinfo --delay 5 /root/hello.jpg &    
    exit 0
}

case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    # No-op
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: asplashscreen [start|stop]" >&2
    exit 3
    ;;
esac

: