#!/bin/sh
#
# Start the usb audio driver
#

case "$1" in
  start)
        echo -n "Starting usb audio driver: "
        modprobe snd_usb_audio
        echo "OK"
        ;;
  stop)
        echo -n "Stopping usb audio driver: "
        rmmod snd_usb_audio
        echo "OK"
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
